#:::::::::::::::::: Deployment definition for k8 ::::::::::::::::::::::
apiVersion: apps/v1 #version of kube-apiserver for ReplicaSet to manage workloads
kind: Deployment #to upgrade the existing ReplicaSet 
metadata: 
  name: myapp-backend-replicaset 
  labels: 
    app: myapp 
    type: backend 
spec: 
  template: 
    metadata:
      name: myapp-backend-pod 
      labels:
        app: myapp-backend 
        type: backend 
    spec:
      containers: 
        - name: nginx-container 
          image: nginx:1.7.1 #specify the upgraded version of image  

  replicas: 3 
  selector: 
    matchLabels: 
      type: backend 
